update=30.04.2018 09:11:03
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=stm32
LibName31=74xgxx
LibName32=ac-dc
LibName33=actel
LibName34=allegro
LibName35=Altera
LibName36=analog_devices
LibName37=battery_management
LibName38=bbd
LibName39=bosch
LibName40=brooktre
LibName41=cmos_ieee
LibName42=dc-dc
LibName43=diode
LibName44=elec-unifil
LibName45=ESD_Protection
LibName46=ftdi
LibName47=gennum
LibName48=graphic
LibName49=hc11
LibName50=ir
LibName51=Lattice
LibName52=leds
LibName53=logo
LibName54=maxim
LibName55=mechanical
LibName56=microchip_dspic33dsc
LibName57=microchip_pic10mcu
LibName58=microchip_pic12mcu
LibName59=microchip_pic16mcu
LibName60=microchip_pic18mcu
LibName61=microchip_pic24mcu
LibName62=microchip_pic32mcu
LibName63=modules
LibName64=motor_drivers
LibName65=motors
LibName66=msp430
LibName67=nordicsemi
LibName68=nxp
LibName69=nxp_armmcu
LibName70=onsemi
LibName71=Oscillators
LibName72=Power_Management
LibName73=powerint
LibName74=pspice
LibName75=references
LibName76=relays
LibName77=rfcom
LibName78=sensors
LibName79=silabs
LibName80=stm8
LibName81=supertex
LibName82=switches
LibName83=transf
LibName84=triac_thyristor
LibName85=ttl_ieee
LibName86=video
LibName87=wiznet
LibName88=Worldsemi
LibName89=Xicor
LibName90=zetex
LibName91=Zilog
LibName92=C:/Users/Mathsterk/Documents/kicad/custom libraries/MATHSTERK/stm32f103-china-ms
LibName93=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/74hct125d
LibName94=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/74hct245
LibName95=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/75176
LibName96=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/acorn_electron_expansion_connector
LibName97=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/arm-swd-header
LibName98=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/esp8266-esp-01
LibName99=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/esp8266-esp-03
LibName100=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/esp8266-esp-12e
LibName101=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/hm-11
LibName102=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/iso15
LibName103=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/lpc11u14fbd48
LibName104=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/mcp1700t-3302e-tt
LibName105=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/mcp73831t-2aci-ot
LibName106=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/micro_usb_socket
LibName107=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/mke02z64vld2
LibName108=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/mke04z8vtg4
LibName109=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/nRF24L01+
LibName110=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/nrf24l01p_smd
LibName111=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/nrf51822-04
LibName112=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/pp_ws2812b
LibName113=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/recom-r1se
LibName114=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/stm32f37xxx_48pin
LibName115=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/stm32f102xx_48pin
LibName116=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/stm32f103c8t6-module-china
LibName117=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/stm32f302xx_48pin
LibName118=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/uart_pp
LibName119=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/usb_plug
LibName120=C:/Users/Mathsterk/Documents/kicad/custom libraries/lib_w_logic/w_logic
LibName121=C:/Users/Mathsterk/Documents/kicad/custom libraries/MATHSTERK/FQP30N06L/FQP30N06L
LibName122=C:/Users/Mathsterk/Documents/kicad/custom libraries/MATHSTERK/ipn70r450p7s
LibName123=C:/Users/Mathsterk/Documents/kicad/custom libraries/MATHSTERK/sw_spst_ms
LibName124=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/4000-ic
LibName125=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/7400-ic
LibName126=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/analog-ic
LibName127=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/avr-mcu
LibName128=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/bluegiga
LibName129=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/connector
LibName130=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/diode-inc-ic
LibName131=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/freescale-ic
LibName132=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/ftdi-ic
LibName133=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/led
LibName134=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/maxim-ic
LibName135=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/micrel-ic
LibName136=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/microchip-ic
LibName137=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/nxp-ic
LibName138=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/on-semi-ic
LibName139=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/regulator
LibName140=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/rohm
LibName141=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/sharp-relay
LibName142=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/sparkfun
LibName143=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/standard
LibName144=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/stmicro-mcu
LibName145=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/ti-ic
LibName146=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/transistor
LibName147=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/uln-ic
LibName148=C:/Users/Mathsterk/Documents/kicad/custom libraries/MATHSTERK/DIVERSE
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[general]
version=1
